"""Optional FastAPI application for the Nastech single-model runtime."""

from __future__ import annotations

import json
from pathlib import Path
from tempfile import TemporaryDirectory

from .service import NastechRenderError, NastechService


def create_app(service: NastechService | None = None):
    """Create a local Nastech HTTP API.

    FastAPI is optional so importing the core package does not require server
    dependencies. Install `nastech-tts[api,local]` before serving requests.
    """
    try:
        from fastapi import FastAPI, HTTPException
        from fastapi.responses import Response
        from pydantic import BaseModel, Field
    except ImportError as exc:
        raise RuntimeError("Install the Nastech [api] extra to create the HTTP application.") from exc

    runtime = service or NastechService()
    app = FastAPI(
        title="Nastech TTS API",
        version="0.2.0",
        description="English expressive speech generated by the single Nastech model family.",
    )

    class SpeechRequest(BaseModel):
        markup: str = Field(..., description="NastechML document to synthesize.")

    @app.get("/v1/health")
    def health() -> dict[str, object]:
        return {"service": "nastech-tts", **runtime.engine_status()}

    @app.get("/v1/models/nastech-voice-en-v1")
    def model() -> dict[str, object]:
        return runtime.model.to_dict()

    @app.post("/v1/audio/speech")
    def speech(request: SpeechRequest):
        try:
            with TemporaryDirectory(prefix="nastech-api-") as temporary_directory:
                output_path = Path(temporary_directory) / "speech.wav"
                result = runtime.render(request.markup, output_path)
                audio = result.audio_path.read_bytes()
                manifest = json.loads(result.manifest_path.read_text(encoding="utf-8"))
        except (ValueError, NastechRenderError) as exc:
            raise HTTPException(status_code=422, detail=str(exc)) from exc
        fidelity = ",".join(decision["fidelity"] for decision in manifest["decisions"])
        return Response(
            content=audio,
            media_type="audio/wav",
            headers={
                "X-Nastech-Model": runtime.model.product_model_id,
                "X-Nastech-Fidelity": fidelity,
            },
        )

    return app
