"""Deterministic local WAV cleanup for Nastech TTS output.

The cleanup stage is deliberately conservative. It does not imitate, replace, or
transform a speaker; it only performs bounded PCM hygiene on mono 16-bit WAV
files generated by the local runtime.
"""

from __future__ import annotations

import io
import struct
import wave
from dataclasses import dataclass
from typing import Any


class VoiceCleanupError(ValueError):
    """Raised when a WAV is unsupported by the conservative local cleanup stage."""


@dataclass(frozen=True)
class CleanedWav:
    """Cleaned PCM WAV bytes plus an auditable local processing report."""

    data: bytes
    report: dict[str, Any]


def _clamp_pcm16(value: float) -> int:
    return max(-32768, min(32767, round(value)))


def clean_wav(
    data: bytes,
    *,
    noise_gate_dbfs: float = -52.0,
    fade_milliseconds: float = 6.0,
) -> CleanedWav:
    """Apply conservative cleanup to mono signed-16-bit PCM WAV audio.

    The stage removes a fixed DC bias, gates only samples near digital silence,
    limits peaks to -0.35 dBFS when required, and fades both edges to prevent
    clicks. It is intentionally deterministic and requires no second TTS or
    voice-conversion model.
    """
    if not data:
        raise VoiceCleanupError("Audio data is empty.")
    if not -80.0 <= noise_gate_dbfs <= -24.0:
        raise VoiceCleanupError("noise_gate_dbfs must be between -80 and -24 dBFS.")
    if not 0.0 <= fade_milliseconds <= 50.0:
        raise VoiceCleanupError("fade_milliseconds must be between 0 and 50.")

    try:
        with wave.open(io.BytesIO(data), "rb") as reader:
            channels = reader.getnchannels()
            sample_width = reader.getsampwidth()
            sample_rate = reader.getframerate()
            compression = reader.getcomptype()
            frame_count = reader.getnframes()
            raw_frames = reader.readframes(frame_count)
    except (EOFError, wave.Error) as exc:
        raise VoiceCleanupError(f"Audio is not a readable WAV file: {exc}") from exc

    if channels != 1 or sample_width != 2 or compression != "NONE":
        raise VoiceCleanupError("Cleanup supports mono 16-bit PCM WAV audio only.")
    if frame_count == 0:
        raise VoiceCleanupError("WAV contains no PCM frames.")
    if len(raw_frames) != frame_count * 2:
        raise VoiceCleanupError("WAV PCM frame data is incomplete.")

    samples = list(struct.unpack(f"<{frame_count}h", raw_frames))
    dc_offset = sum(samples) / frame_count
    centered = [_clamp_pcm16(sample - dc_offset) for sample in samples]
    gate_threshold = max(1, round(32767 * (10 ** (noise_gate_dbfs / 20))))
    gated_count = 0
    for index, sample in enumerate(centered):
        if abs(sample) <= gate_threshold:
            centered[index] = 0
            gated_count += 1

    peak_before = max(abs(sample) for sample in centered)
    target_peak = round(32767 * (10 ** (-0.35 / 20)))
    gain = min(1.0, target_peak / peak_before) if peak_before else 1.0
    if gain < 1.0:
        centered = [_clamp_pcm16(sample * gain) for sample in centered]

    fade_samples = min(round(sample_rate * fade_milliseconds / 1000), frame_count // 2)
    if fade_samples:
        for index in range(fade_samples):
            scale = (index + 1) / fade_samples
            centered[index] = _clamp_pcm16(centered[index] * scale)
            tail_index = frame_count - 1 - index
            centered[tail_index] = _clamp_pcm16(centered[tail_index] * scale)

    output_frames = struct.pack(f"<{frame_count}h", *centered)
    output_buffer = io.BytesIO()
    with wave.open(output_buffer, "wb") as writer:
        writer.setnchannels(1)
        writer.setsampwidth(2)
        writer.setframerate(sample_rate)
        writer.writeframes(output_frames)

    cleaned = output_buffer.getvalue()
    return CleanedWav(
        data=cleaned,
        report={
            "processor": "nastech-local-pcm-cleanup",
            "format": "mono-16-bit-pcm-wav",
            "sample_rate": sample_rate,
            "duration_seconds": round(frame_count / sample_rate, 4),
            "dc_offset_removed": round(dc_offset, 4),
            "noise_gate_dbfs": noise_gate_dbfs,
            "noise_gate_samples": gated_count,
            "peak_before": peak_before,
            "peak_after": max(abs(sample) for sample in centered),
            "limiter_gain": round(gain, 6),
            "fade_milliseconds": fade_milliseconds,
            "input_bytes": len(data),
            "output_bytes": len(cleaned),
        },
    )
